from rsf.proj import *

__author__ = "Geofisicando"
__version__ = "1.0.0"
__site__ = "www.geofisicando.com"

Help('''
 Denoising Flow
 ==============

 Author: %s
 Version: %s
 Site: %s
 ''' % (__author__,__version__,__site__))

Help(''' 1 - Create velocity model and dataset''')

Flow('vrms',None,'math d1=0.004 n1=1001 o1=0 output="x1*125+2000"')

Flow('synt','vrms',
	'''
	spike d1=0.004 n1=1001 o1=0 nsp=17 n2=128 d2=20 o2=0
	label2=Offset unit2=m
	k1=%s
	mag=1,1,1,1,-1,1,1,-1,1,1,1,-1,1,1,-1,1,1 |
	bandpass flo=4 fhi=20 |
	inmo velocity=$SOURCE half=n
	''' % ",".join(map(str,range(100,916,48))) )

End()












